# Generated by Django 5.0.4 on 2024-04-25 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_family_invitation_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('tag', models.CharField(blank=True, choices=[('E', 'Учеба'), ('Работа', 'Работа'), ('Дет. сад', 'Детский сад'), ('Здоровье', 'Здоровье'), ('Уборка', 'Уборка'), ('Пища', 'Пища'), ('Развлечения', 'Развлечения')], max_length=11, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Ожидает', 'Ожидает'), ('Выполняется', 'Выполняется'), ('Завершена', 'Завершена'), ('Не выполнена', 'Не выполнена')], max_length=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.family')),
            ],
        ),
    ]
