# Generated by Django 5.0.4 on 2024-04-25 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role',
            new_name='FamilyRole',
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appuser')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.family')),
            ],
        ),
    ]
