# Generated by Django 5.0.4 on 2024-05-31 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_appuser_email_alter_appuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedToken',
            fields=[
                ('jti', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked', models.BooleanField(default=False)),
                ('device_id', models.UUIDField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appuser')),
            ],
        ),
    ]
