# Generated by Django 5.0.4 on 2024-06-03 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_issuedtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tag',
            field=models.CharField(blank=True, choices=[('Учеба', 'Учеба'), ('Работа', 'Работа'), ('Дет. сад', 'Детский сад'), ('Здоровье', 'Здоровье'), ('Уборка', 'Уборка'), ('Еда', 'Еда'), ('Развлечения', 'Развлечения')], max_length=11, null=True),
        ),
        migrations.CreateModel(
            name='TaskRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Owner', 'Owner'), ('Editor', 'Editor'), ('Executor', 'Executor')], max_length=8)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appuser')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.task')),
            ],
        ),
    ]
