# Generated by Django 5.0.4 on 2024-06-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_task_tag_taskrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tag',
            field=models.CharField(choices=[('Учеба', 'Учеба'), ('Работа', 'Работа'), ('Дет. сад', 'Детский сад'), ('Здоровье', 'Здоровье'), ('Уборка', 'Уборка'), ('Еда', 'Еда'), ('Развлечения', 'Развлечения')], max_length=11, null=True),
        ),
    ]
