# Generated by Django 5.0.4 on 2024-06-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_task_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='private',
            field=models.CharField(choices=[('Личное', 'Личное'), ('Для этой семьи', 'Для этой семьи'), ('Для всех', 'Для всех')], default='Для всех', max_length=24),
        ),
    ]
