# Generated by Django 5.0.4 on 2024-06-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_task_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='family',
        ),
        migrations.AlterField(
            model_name='task',
            name='private',
            field=models.CharField(choices=[('Личное', 'Личное'), ('Для этой семьи', 'Для этой семьи'), ('Для всех', 'Для всех')], max_length=24),
        ),
        migrations.AlterField(
            model_name='task',
            name='tag',
            field=models.CharField(choices=[('Учеба', 'Учеба'), ('Работа', 'Работа'), ('Дети', 'Дети'), ('Здоровье', 'Здоровье'), ('Уборка', 'Уборка'), ('Еда', 'Еда'), ('Развлечения', 'Развлечения')], max_length=11, null=True),
        ),
    ]
