# Generated by Django 5.0.4 on 2024-06-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_notification_family_alter_task_private_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='tag',
            field=models.CharField(choices=[('Task', 'Task'), ('Memeber', 'Member'), ('Family', 'Family')], default='Task', max_length=12),
            preserve_default=False,
        ),
    ]
