version: '3.8'

services:
  postgres:
    image: postgres:16.2-bullseye
    container_name: postgres_fam
    environment:
      POSTGRES_USER: "post"
      POSTGRES_PASSWORD: "post"
      POSTGRES_DB: "post"
    ports:
      - "5432:5432"
    volumes:
      - ./db_post:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U post"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    image: nooonchill/web:1.0
    build: .
    container_name: web_fam
    command: >
      sh -c "python src/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8001:8000"
    depends_on:
      postgres:
        condition: service_healthy
  nginx:
    image: nginx:1.24.0-bullseye
    depends_on:
      - api
    ports:
      - "81:80"
    volumes:
      - /etc/:/etc/
